//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examensarbete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalenderBoking
    {
        public int Id { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Name { get; set; }
        public int NumberOfPeople { get; set; }
    }
}
